name: main

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  packages:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24.x
      - run: corepack enable pnpm

      # pnpm cache
      - id: pnpm
        run: echo "cache-dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: ${{ steps.pnpm.outputs.cache-dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24.x
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        env:
          NODE_ENV: production
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24.x
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint --max-warnings=0
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24.x
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm prettier --check .
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24.x
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm type-check
